### ISSUE TITLE
브라우저 추가 지원

### ISSUE THREAD

**Issue by mu-hun** [BetaF1sh/elearn#1]
`<iframe id="bodyFrame" src="/Lesson.do?cmd=viewStudyContentsWait"`

내 랩탑에서만 그런가 모르겠는데, 임베딩 콘텐츠의 주소가 바뀌질 않고 있다..

**Comment by BetaF1sh** [comment]
## 참조 없이 기다리기

> 내 랩탑에서만 그런가 모르겠는데, 임베딩 콘텐츠의 주소가 바뀌질 않고 있다..

FireFox, Safari 둘다 로딩보다 참조가 우선적으로 이루어지면 `src` 값을 불러오지 않는다.
